// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7emNY4ARdGumQGF7EiSty1kezIxPg5uo',
    appId: '1:637357029596:web:3461e336bcf8d587679c19',
    messagingSenderId: '637357029596',
    projectId: 'agro-baba',
    authDomain: 'agro-baba.firebaseapp.com',
    storageBucket: 'agro-baba.appspot.com',
    measurementId: 'G-W7GJ64EG3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrMHyw6TXqdwK9Wda4TyYJ1H7xUIvMdZw',
    appId: '1:637357029596:android:e4bd2e3e69687e39679c19',
    messagingSenderId: '637357029596',
    projectId: 'agro-baba',
    storageBucket: 'agro-baba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwC3qIBxzGH-lqDr_OPXvPMq3-WvOJZtw',
    appId: '1:637357029596:ios:42c1c9b75e859ae8679c19',
    messagingSenderId: '637357029596',
    projectId: 'agro-baba',
    storageBucket: 'agro-baba.appspot.com',
    iosBundleId: 'com.example.kishanSe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwC3qIBxzGH-lqDr_OPXvPMq3-WvOJZtw',
    appId: '1:637357029596:ios:42c1c9b75e859ae8679c19',
    messagingSenderId: '637357029596',
    projectId: 'agro-baba',
    storageBucket: 'agro-baba.appspot.com',
    iosBundleId: 'com.example.kishanSe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7emNY4ARdGumQGF7EiSty1kezIxPg5uo',
    appId: '1:637357029596:web:2a65c02183f5d561679c19',
    messagingSenderId: '637357029596',
    projectId: 'agro-baba',
    authDomain: 'agro-baba.firebaseapp.com',
    storageBucket: 'agro-baba.appspot.com',
    measurementId: 'G-WQYHCEZ6WQ',
  );

}