// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOQA2U46jgvuOpGPXwigMQPsmIPYLekqM',
    appId: '1:1053006835682:web:dcedcb2381c06d3fbfd3bb',
    messagingSenderId: '1053006835682',
    projectId: 'kisan-4074a',
    authDomain: 'kisan-4074a.firebaseapp.com',
    storageBucket: 'kisan-4074a.appspot.com',
    measurementId: 'G-TMD76TNHDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJnxojXPlgVM6uFoiRZAcOINLLpMz3IK8',
    appId: '1:1053006835682:android:91d2387624053b12bfd3bb',
    messagingSenderId: '1053006835682',
    projectId: 'kisan-4074a',
    storageBucket: 'kisan-4074a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC94WrlUv9vnpnra_X6-b5kzqsEXt-AJ4M',
    appId: '1:1053006835682:ios:41fed55df50be2edbfd3bb',
    messagingSenderId: '1053006835682',
    projectId: 'kisan-4074a',
    storageBucket: 'kisan-4074a.appspot.com',
    androidClientId: '1053006835682-sfgvmnbnj8q6h7r3mamjbqsrvti9rk3a.apps.googleusercontent.com',
    iosClientId: '1053006835682-ed5hrgt7tss53c0h156mnaphfu2v66gi.apps.googleusercontent.com',
    iosBundleId: 'com.example.kishanSe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC94WrlUv9vnpnra_X6-b5kzqsEXt-AJ4M',
    appId: '1:1053006835682:ios:41fed55df50be2edbfd3bb',
    messagingSenderId: '1053006835682',
    projectId: 'kisan-4074a',
    storageBucket: 'kisan-4074a.appspot.com',
    androidClientId: '1053006835682-sfgvmnbnj8q6h7r3mamjbqsrvti9rk3a.apps.googleusercontent.com',
    iosClientId: '1053006835682-ed5hrgt7tss53c0h156mnaphfu2v66gi.apps.googleusercontent.com',
    iosBundleId: 'com.example.kishanSe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOQA2U46jgvuOpGPXwigMQPsmIPYLekqM',
    appId: '1:1053006835682:web:4344c43159244438bfd3bb',
    messagingSenderId: '1053006835682',
    projectId: 'kisan-4074a',
    authDomain: 'kisan-4074a.firebaseapp.com',
    storageBucket: 'kisan-4074a.appspot.com',
    measurementId: 'G-HTQ7NYR6F1',
  );
}
